# Generated by Django 5.0.2 on 2024-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='media/blog_content_files'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/blog_content_files'),
        ),
        migrations.AlterField(
            model_name='fanbase',
            name='image',
            field=models.ImageField(upload_to='media/fanbase_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product_images/'),
        ),
    ]
