# Generated by Django 5.0.2 on 2024-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blog_image_alter_blogcontent_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog_content_files'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog_content_files'),
        ),
        migrations.AlterField(
            model_name='fanbase',
            name='image',
            field=models.ImageField(upload_to='fanbase_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
