# Generated by Django 5.0.2 on 2024-07-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blog_image_alter_blogcontent_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
